version: '3.8'

networks:
    over-network:

volumes:
    app-data:
    db:
        driver: local
services:
    webserver:
        image: nginx:1.21.6-alpine
        container_name: over-web
        hostname: over.host
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - .docker/nginx:/etc/nginx/conf.d
        networks:
            over-network:
        depends_on:
            - backend
            - mysql

    backend:
        build:
            context: .docker/php
            dockerfile: dockerfile
        container_name: over-backend
        volumes:
            - ./:/var/www
            - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            over-network:
    mysql:
        image: mariadb
        container_name: over-db
        ports:
            - "3306:3306"
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: overhaulmng
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        restart: unless-stopped
        networks:
            over-network:

